Remove closing php tags
WordPress/twentysixteen pull request #497
Opened 2017-03-07 07:10 UTC by vishalkakadiya

2017-03-07 22:03 UTC, ntwb requested changes
I've added a couple of requests/questions.

2017-03-07 22:03 UTC, ntwb commented on functions.php
> +		$b = hexdec( substr( $color, 2, 1 ) . substr( $color, 2, 1 ) );
The above 3 changes should not be in this pull request, can you remove these please @vishalkakadiya

2017-03-07 22:03 UTC, ntwb commented on template-parts/content-search.php
> -
Why is this blank line removed?

2017-03-07 22:05 UTC, ntwb commented
Note: Please do not merge this PR until a decision/consensus has been agreed upon for what themes to make these changes to as part of https://core.trac.wordpress.org/ticket/40039

2017-03-08 05:36 UTC, vishalkakadiya commented on functions.php
> +		$b = hexdec( substr( $color, 2, 1 ) . substr( $color, 2, 1 ) );
@ntwb  I am removing this but, without fixing this **travis** build was **failed**, so, that's why I fixed it and travis pass the built. But don't worry removing it.

2017-03-08 22:01 UTC, ntwb commented on functions.php
> +		$b = hexdec( substr( $color, 2, 1 ) . substr( $color, 2, 1 ) );
Thanks, can you create a sperate pull request with this change then please, then add a link to it on the #498 PR, please, and thank you

2017-03-08 22:02 UTC, ntwb commented
This pull request is now superseded by #498, @vishalkakadiya please close this pull request

2017-06-15 12:35 UTC, closed without merging